# Generated by Django 2.2.6 on 2019-10-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expenditure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='expenditure_type',
            new_name='type',
        ),
    ]
